#source 'https://gitcafe.com/akuandev/Specs.git'
platform :ios, "8.0"
use_frameworks!
target "BookReader" do
    pod 'Alamofire', '~> 3.4'               #pod 'AFNetworking'
    pod 'AlamofireImage', '~> 2.0'          #pod 'YYWebImage'
    pod 'ObjectMapper'                      #pod 'Mantle' #pod 'AlamofireObjectMapper', '~> 3.0'
    pod 'SnapKit'                           #pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'SDCycleScrollView','~> 1.64'
    pod 'MJRefresh'
    pod 'IQKeyboardManagerSwift'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'RealmSwift'
    pod 'SweetAlert', :git => 'https://github.com/codestergit/SweetAlert-iOS.git'                       #pod 'LGAlertView'
    pod 'XCGLogger', '~> 3.3'               #pod 'CocoaLumberjack'
    pod 'XLPagerTabStrip', '~> 5.0'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'LGHelper', :git => 'https://github.com/smartdj/LGHelper.git'
    pod 'RTRootNavigationController'#, :git => 'https://github.com/rickytan/RTRootNavigationController.git'
    pod 'NightNight'#夜间模式
    pod 'TYAttributedLabel', '~> 2.6.2'#coretext
end



#Installing Alamofire 3.4.2 (was 3.4.0)
#Installing AlamofireImage 2.4.1 (was 2.4.0)
#Installing IQKeyboardManagerSwift 4.0.5 (was 4.0.3)
#Installing LGHelper 1.1.2 (was 1.1.2)
#Installing MBProgressHUD 1.0.0 (was 0.9.2)
#Installing MJRefresh 3.1.12 (was 3.1.0)
#Installing NightNight (0.3.1)
#Installing ObjectMapper 1.4.0 (was 1.3.0)
#Installing RTRootNavigationController (0.5.20)
#Installing Realm 1.0.2 (was 1.0.0)
#Installing RealmSwift 1.0.2 (was 1.0.0)
#Using Reveal-iOS-SDK (1.6.2)
#Using SDCycleScrollView (1.65)
#Installing SDWebImage 3.8.1 (was 3.7.6)
#Installing SnapKit 0.22.0 (was 0.21.0)
#Installing SweetAlert 0.1.0 (was 0.1.0)
#Installing TYAttributedLabel (2.6.2)
#Using UITableView+FDTemplateLayoutCell (1.4)
#Installing XCGLogger 3.5.1 (was 3.3)
#Using XLPagerTabStrip (5.0.0)
