#source 'https://gitcafe.com/akuandev/Specs.git'
platform :ios, "8.0"
use_frameworks!
target "BookReader" do
    pod 'Alamofire', '~> 3.4'               #pod 'AFNetworking'
    pod 'AlamofireImage', '~> 2.0'          #pod 'YYWebImage'
    pod 'ObjectMapper'                      #pod 'Mantle' #pod 'AlamofireObjectMapper', '~> 3.0'
    pod 'SnapKit'                           #pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'SDCycleScrollView','~> 1.64'
    pod 'MJRefresh'
    pod 'IQKeyboardManagerSwift'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'RealmSwift'
    pod 'SweetAlert', :git => 'https://github.com/codestergit/SweetAlert-iOS.git'                       #pod 'LGAlertView'
    pod 'XCGLogger', '~> 3.3'               #pod 'CocoaLumberjack'
    pod 'XLPagerTabStrip', '~> 5.0'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'LGHelper', :git => 'https://github.com/smartdj/LGHelper.git'
    pod 'RTRootNavigationController'#, :git => 'https://github.com/rickytan/RTRootNavigationController.git'
    pod 'NightNight'#夜间模式
    pod 'TYAttributedLabel', '~> 2.6.2'#coretext
    pod 'SWTableViewCell'#带很多手势的表单元格。
    #pod 'iOSSlideMenu', :git => 'https://github.com/smartdj/iOSSlideMenu.git'#侧边菜单
    pod 'PKRevealController'
end



#Using Alamofire (3.4.2)
#Using AlamofireImage (2.4.1)
#Using IQKeyboardManagerSwift (4.0.5)
#Installing LGHelper 1.1.2 (was 1.1.2)
#Using MBProgressHUD (1.0.0)
#Using MJRefresh (3.1.12)
#Using NightNight (0.3.1)
#Using ObjectMapper (1.4.0)
#Installing PKRevealController (2.0.6)
#Using RTRootNavigationController (0.5.20)
#Using Realm (1.0.2)
#Using RealmSwift (1.0.2)
#Using Reveal-iOS-SDK (1.6.2)
#Using SDCycleScrollView (1.65)
#Using SDWebImage (3.8.1)
#Using SWTableViewCell (0.3.7)
#Using SnapKit (0.22.0)
#Installing SweetAlert 0.1.0 (was 0.1.0)
#Using TYAttributedLabel (2.6.2)
#Using UITableView+FDTemplateLayoutCell (1.4)
#Using XCGLogger (3.5.1)
#Using XLPagerTabStrip (5.0.0)